//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPortfolio.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PortfolioDBEntities : DbContext
    {
        public PortfolioDBEntities()
            : base("name=PortfolioDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_AboutUs> tbl_AboutUs { get; set; }
        public virtual DbSet<tbl_Educations> tbl_Educations { get; set; }
        public virtual DbSet<tbl_Experiences> tbl_Experiences { get; set; }
        public virtual DbSet<tbl_Profile> tbl_Profile { get; set; }
        public virtual DbSet<tbl_Skills> tbl_Skills { get; set; }
        public virtual DbSet<tbl_User> tbl_User { get; set; }
    }
}
