//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPortfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Educations
    {
        public int Education_id { get; set; }
        public Nullable<int> User_id { get; set; }
        public string SchoolName { get; set; }
        public string Field { get; set; }
        public string StartingDate { get; set; }
        public string GraduationDate { get; set; }
        public string EducationDetail { get; set; }
    }
}
